version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    container_name: node_adns
    ports:
      - '8000:8000'
    volumes:
      - .:/adns
      # - '/adns/node_modules'
    tty: true
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql_adns
    env_file: ./mysql/mysql.env
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d/:ro
volumes:
  my-db:
